import { Artist } from '@/types';

export const artists: Artist[] = [
  {
    slug: 'bts',
    name: 'BTS',
    type: 'group',
    agency: 'HYBE / BIGHIT MUSIC',
    debut: '2013-06-13',
    members: ['RM', 'Jin', 'SUGA', 'J-Hope', 'Jimin', 'V', 'Jungkook'],
    description: 'Global phenomenon and one of the best-selling music artists of all time, known for mixing hip-hop, pop, and R&B with introspective lyrics.',
    symbol: '🪄',
    brandColor: '#7C3AED',
    logo: '/images/artists/bts.svg',
    tags: ['BTS', 'Jungkook', 'Jimin', 'V', 'RM', 'Jin', 'SUGA', 'J-Hope', 'Bangtan'],
    socialLinks: { twitter: 'https://twitter.com/BTS_twt' },
  },
  {
    slug: 'blackpink',
    name: 'BLACKPINK',
    type: 'group',
    agency: 'YG Entertainment',
    debut: '2016-08-08',
    members: ['Jisoo', 'Jennie', 'Rosé', 'Lisa'],
    description: 'One of the highest-charting Korean acts in history, known for their bold fashion, fierce performance style, and global influence.',
    symbol: '🌹',
    brandColor: '#EC4899',
    logo: '/images/artists/blackpink.svg',
    tags: ['BLACKPINK', 'Jennie', 'Jisoo', 'Rosé', 'Lisa'],
    socialLinks: { twitter: 'https://twitter.com/BLACKPINK' },
  },
  {
    slug: 'enhypen',
    name: 'ENHYPEN',
    type: 'group',
    agency: 'BELIFT LAB (HYBE)',
    debut: '2020-11-30',
    members: ['Jungwon', 'Heeseung', 'Jay', 'Jake', 'Sunghoon', 'Sunoo', 'Ni-ki'],
    description: 'Formed through the reality show I-LAND, ENHYPEN blends dark concepts with youthful energy and impressive choreography.',
    symbol: '🌙',
    brandColor: '#1E3A8A',
    logo: '/images/artists/enhypen.svg',
    tags: ['ENHYPEN', 'Heeseung', 'Jungwon', 'Jay', 'Jake', 'Sunghoon', 'Sunoo', 'Ni-ki'],
  },
  {
    slug: 'aespa',
    name: 'aespa',
    type: 'group',
    agency: 'SM Entertainment',
    debut: '2020-11-17',
    members: ['Karina', 'Giselle', 'Winter', 'Ningning'],
    description: 'Pioneers of the "metaverse K-Pop" concept, each member has a virtual avatar counterpart in the SM Culture Universe.',
    symbol: '⚡',
    brandColor: '#059669',
    logo: '/images/artists/aespa.svg',
    tags: ['aespa', 'Karina', 'Giselle', 'Winter', 'Ningning'],
  },
  {
    slug: 'seventeen',
    name: 'SEVENTEEN',
    type: 'group',
    agency: 'PLEDIS Entertainment (HYBE)',
    debut: '2015-05-26',
    members: ['S.Coups', 'Jeonghan', 'Joshua', 'Jun', 'Hoshi', 'Wonwoo', 'Woozi', 'DK', 'Mingyu', 'The8', 'Seungkwan', 'Vernon', 'Dino'],
    description: 'Known as a "self-producing" group, SEVENTEEN writes and produces most of their own music and choreography.',
    symbol: '💎',
    brandColor: '#D97706',
    logo: '/images/artists/seventeen.svg',
    tags: ['SEVENTEEN', 'SVT'],
  },
  {
    slug: 'twice',
    name: 'TWICE',
    type: 'group',
    agency: 'JYP Entertainment',
    debut: '2015-10-20',
    members: ['Nayeon', 'Jeongyeon', 'Momo', 'Sana', 'Jihyo', 'Mina', 'Dahyun', 'Chaeyoung', 'Tzuyu'],
    description: 'One of the top-selling girl groups of all time, known for catchy pop songs and strong global fanbase called ONCE.',
    symbol: '🦋',
    brandColor: '#EF4444',
    logo: '/images/artists/twice.svg',
    tags: ['TWICE', 'Nayeon', 'Sana', 'Jihyo', 'Tzuyu'],
  },
  {
    slug: 'ive',
    name: 'IVE',
    type: 'group',
    agency: 'Starship Entertainment',
    debut: '2021-12-01',
    members: ['Yujin', 'Gaeul', 'Rei', 'Wonyoung', 'Liz', 'Leeseo'],
    description: 'Award-winning 4th gen girl group known for confident, elegant concepts and mega-hit singles.',
    symbol: '🌟',
    brandColor: '#8B5CF6',
    logo: '/images/artists/ive.svg',
    tags: ['IVE', 'Wonyoung', 'Yujin', 'Rei'],
  },
  {
    slug: 'stray-kids',
    name: 'Stray Kids',
    type: 'group',
    agency: 'JYP Entertainment',
    debut: '2018-03-25',
    members: ['Bang Chan', 'Lee Know', 'Changbin', 'Hyunjin', 'Han', 'Felix', 'Seungmin', 'I.N'],
    description: 'Self-producing group known for hard-hitting performances, complex concepts, and the iconic unit "3RACHA".',
    symbol: '🔥',
    brandColor: '#DC2626',
    logo: '/images/artists/stray-kids.svg',
    tags: ['Stray Kids', 'SKZ', 'Bang Chan', 'Hyunjin', 'Felix'],
  },
  {
    slug: 'ateez',
    name: 'ATEEZ',
    type: 'group',
    agency: 'KQ Entertainment',
    debut: '2018-10-24',
    members: ['Hongjoong', 'Seonghwa', 'Yunho', 'Yeosang', 'San', 'Mingi', 'Wooyoung', 'Jongho'],
    description: 'Renowned for explosive stage presence and a unique pirate-themed concept that spans their entire discography.',
    symbol: '⚓',
    brandColor: '#B45309',
    logo: '/images/artists/ateez.svg',
    tags: ['ATEEZ'],
  },
  {
    slug: 'newjeans',
    name: 'NewJeans',
    type: 'group',
    agency: 'ADOR (HYBE)',
    debut: '2022-07-22',
    members: ['Minji', 'Hanni', 'Danielle', 'Haerin', 'Hyein'],
    description: 'Broke records with a retro-Y2K aesthetic and casual, natural concept that redefined 4th-gen girl group standards.',
    symbol: '🐇',
    brandColor: '#3B82F6',
    logo: '/images/artists/newjeans.svg',
    tags: ['NewJeans', 'Minji', 'Hanni', 'Danielle', 'Haerin', 'Hyein'],
  },
  {
    slug: 'illit',
    name: 'ILLIT',
    type: 'group',
    agency: 'BELIFT LAB (HYBE)',
    debut: '2024-03-25',
    members: ['Yunah', 'Minju', 'Moka', 'Wonhee', 'Iroha'],
    description: 'Formed through the survival show R U Next?, ILLIT debuted with the hit single "Magnetic".',
    symbol: '🌸',
    brandColor: '#F472B6',
    logo: '/images/artists/illit.svg',
    tags: ['ILLIT'],
  },
  {
    slug: 'txt',
    name: 'TXT (Tomorrow X Together)',
    type: 'group',
    agency: 'HYBE / BIGHIT MUSIC',
    debut: '2019-03-04',
    members: ['Yeonjun', 'Soobin', 'Beomgyu', 'Taehyun', 'Huening Kai'],
    description: 'Known for conceptual storytelling and eclectic genre-blending, TXT explores themes of youth, dreams, and darkness.',
    symbol: '🌀',
    brandColor: '#6366F1',
    logo: '/images/artists/txt.jpg',
    tags: ['TXT', 'Tomorrow X Together', 'Yeonjun', 'Soobin'],
  },
  {
    slug: 'riize',
    name: 'RIIZE',
    type: 'group',
    agency: 'SM Entertainment',
    debut: '2023-09-04',
    members: ['Shotaro', 'Eunseok', 'Sungchan', 'Wonbin', 'Seunghan', 'Anton', 'Sohee'],
    description: 'SM Entertainment\'s 4th-gen boy group with a fresh, vibrant pop sound and strong visual identity.',
    symbol: '☀️',
    brandColor: '#F97316',
    logo: '/images/artists/riize.svg',
    tags: ['RIIZE'],
  },
  {
    slug: 'zerobaseone',
    name: 'ZEROBASEONE',
    type: 'group',
    agency: 'WakeOne',
    debut: '2023-07-10',
    members: ['Sung Hanbin', 'Kim Jiwoong', 'Zhang Hao', 'Seok Matthew', 'Kim Taerae', 'Ricky', 'Kim Gyuvin', 'Park Gunwook', 'Han Yujin'],
    description: 'Formed through the survival show Boys Planet, ZB1 quickly became one of the most talked-about 4th-gen boy groups.',
    symbol: '⭐',
    brandColor: '#10B981',
    logo: '/images/artists/zerobaseone.png',
    tags: ['ZEROBASEONE', 'ZB1'],
  },
  {
    slug: 'katseye',
    name: 'KATSEYE',
    type: 'group',
    agency: 'HYBE / Geffen Records',
    debut: '2024-06-26',
    members: ['Sophia', 'Daniela', 'Manon', 'Lara', 'Megan', 'Yoonchae'],
    description: 'International girl group formed through the Netflix series "Pop Star Academy: KATSEYE", signed under both HYBE and Geffen Records.',
    symbol: '👁️',
    brandColor: '#7C3AED',
    logo: '/images/artists/katseye.svg',
    tags: ['KATSEYE', 'Manon'],
  },
  {
    slug: 'nct',
    name: 'NCT',
    type: 'group',
    agency: 'SM Entertainment',
    debut: '2016-04-09',
    members: ['Taeil', 'Johnny', 'Taeyong', 'Yuta', 'Kun', 'Doyoung', 'Ten', 'Jaehyun', 'Jungwoo', 'Mark', 'Xiaojun', 'Hendery', 'Renjun', 'Jeno', 'Haechan', 'Jaemin', 'Yangyang', 'Shotaro', 'Sungchan', 'Chenle', 'Jisung', 'Sicheng'],
    description: 'SM Entertainment\'s neo culture technology concept group with an "unlimited member" system, encompassing sub-units NCT U, NCT 127, NCT Dream, WayV, and NCT WISH.',
    symbol: '🌐',
    brandColor: '#16A34A',
    tags: ['NCT', 'NCT 127', 'NCT Dream', 'WayV', 'Mark', 'Haechan', 'Taeyong', 'Doyoung', 'Jeno', 'Jaemin', 'Renjun'],
  },
  {
    slug: 'le-sserafim',
    name: 'LE SSERAFIM',
    type: 'group',
    agency: 'HYBE / Source Music',
    debut: '2022-05-02',
    members: ['Sakura', 'Kim Chaewon', 'Huh Yunjin', 'Kazuha', 'Hong Eunchae'],
    description: 'HYBE\'s fierce and athletic girl group known for their powerful choreography, bold concepts, and "I am fearless" motto.',
    symbol: '🔥',
    brandColor: '#DC2626',
    tags: ['LE SSERAFIM', 'Sakura', 'Chaewon', 'Yunjin', 'Kazuha', 'Eunchae', 'LESSERAFIM'],
  },
  {
    slug: 'red-velvet',
    name: 'Red Velvet',
    type: 'group',
    agency: 'SM Entertainment',
    debut: '2014-08-01',
    members: ['Irene', 'Seulgi', 'Wendy', 'Joy', 'Yeri'],
    description: 'SM Entertainment\'s versatile girl group known for their unique dual concept of "Red" (upbeat, fun) and "Velvet" (sophisticated, sensual).',
    symbol: '🌹',
    brandColor: '#BE123C',
    tags: ['Red Velvet', 'Irene', 'Seulgi', 'Wendy', 'Joy', 'Yeri'],
  },
];

export function getArtistBySlug(slug: string): Artist | undefined {
  return artists.find((a) => a.slug === slug);
}

export function getArtistByTag(tag: string): Artist | undefined {
  return artists.find((a) =>
    a.tags.some((t) => t.toLowerCase() === tag.toLowerCase())
  );
}

export function getAllArtistSlugs(): string[] {
  return artists.map((a) => a.slug);
}
